### ISSUE TITLE
golang/go/wiki/ResearchPapers

### ISSUE THREAD

**Issue by ImreSamu** [nickng/dingo-hunter#13]
Hi! 
this paper is removed from  [golang/go/wiki/ResearchPapers](https://github.com/golang/go/wiki/ResearchPapers)    :disappointed: 

https://github.com/golang/go/wiki/ResearchPapers/_compare/fa4bab02ff787e6bb52ec71b43715afdd0a54948...7d15ba891fb30cb1c98dd1062b1853af937adb7c
history:  https://github.com/golang/go/wiki/ResearchPapers/_history

Is it  possible to re-add ?  ( or revert changes ? )

**Comment by nickng** [comment]
Unfortunately there are some mistakes in the paper, and the paper will not be published as of now :disappointed:, so we have taken the paper offline - I'll add it back on the wiki as soon as we're happy with the fix.

The tools are still online so feel free to play around with it!

**Comment by ImreSamu** [comment]
thank you for you answers!  I hope it will be soon!
